### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by touahriayacine** [TaiLvYuanLiang/HGWaveNet#1]
Hello, I hope you are doing well. If I may, I would like to ask if you could provide a README file. It would be helpful to include a few examples on how to run the model with different configurations and outline the preprocessing steps for the dataset before passing it through this model. Thank you in advance.

**Comment by TaiLvYuanLiang** [comment]
Thanks for your concern for our study. We have uploaded a README file [README.md](https://github.com/TaiLvYuanLiang/HGWaveNet/blob/main/README.md) to provide more information to run our code and we hope it helps.

**Comment by touahriayacine** [comment]
Thank you for replying to my question, and I appreciate that you did it on short notice.
